image: docker:git

stages:
  - test

cache:
  paths:
    - vendor/

variables:
  DOCKER_DRIVER: overlay
  DOCKER_COMPOSE: "docker-compose -f docker-compose.yml"

services:
  #- docker:stable-dind
  - docker:18.09.7-dind

test_phpunit:
  stage: test
#  except:
#    - master
  script:
    - apk add --update py-pip python-dev libffi-dev openssl-dev gcc libc-dev make && pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - $DOCKER_COMPOSE pull
    - $DOCKER_COMPOSE up -d
    - sleep 20
#    - > # wait for creating Postgres Database
#      while ! $($DOCKER_COMPOSE exec -T pgsql psql -U postgres -d sps -c "select 1" > /dev/null 2>&1); do
#        sleep 1;
#      done;
#    #- $DOCKER_COMPOSE exec -T mysql mysql -u root -D sps -e "select 1"
#    - > # wait for creating MySql Database
#      while ! $($DOCKER_COMPOSE exec -T mysql mysql -u root -D sps -e "select 1") > /dev/null 2>&1; do
#        sleep 1;
#      done;
    - $DOCKER_COMPOSE exec -T php /usr/local/bin/composer install
    - $DOCKER_COMPOSE exec -T php echo $PHPUNIT_XML > phpunit.xml
    - $DOCKER_COMPOSE exec -T php vendor/phpunit/phpunit/phpunit
