language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1
    - 7.2

before-install:
  - composer self-update

install:
    - composer update

script:
    - php ./vendor/phpunit/phpunit/phpunit
